### ISSUE TITLE
Что, если имя, фамилия и телефон совпали?

### ISSUE THREAD

**Issue by dvaschenko** [alkhachaturian/homework-6#1]
````
String email = dataManager.loadValue("select c.email from Client c where c.firstName = :firstName " +
                        "and c.lastName = :lastName and c.telephone = :phone", String.class)
                .setParameters(Map.of("firstName", client.getFirstName(), "lastName", client.getLastName(),
                        "phone", client.getTelephone()))
                .one();
````
Код работает, но выглядит спорным ). Вспомните, что всегда будет загружено, даже если не используется никакой фетч-план и в кастомном фетч-плане нет ни одного указанного поля

**Comment by alkhachaturian** [comment]
npe, исправила

**Comment by dvaschenko** [comment]
Хотел обратить внимание немного на другое ))) При загрузке экземпляра из базы данных без указания фетч плана и вообще без указания каких либо полей, будет загружен только UUID сущности (или кастомный ID). Он будет загружен всегда, даже если фетч план пустой, и в экземпляре будет только он. Потом уже можно повторно загрузить сущность по ID вот так:

**Comment by dvaschenko** [comment]
Задание принято, исправление последнего замечания на Ваше усмотрение
В целом все решения очень хорошие, в некоторых даже дополнительные улучшения сверх задания. Отличная работа

**Comment by alkhachaturian** [comment]
спасибо
